backend:
  name: git-gateway
  repo: ehylam/gatsby-blog

media_folder: static/assets
public_folder: /assets

collections:
  - name: content
    label: Content
    folder: src/pages/contents
    create: true
    slug: "{{year}}-{{heading}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-module"}
      - {label: "Heading", name: "heading", widget: "string"}
      - {label: "Subheading", name: "subheading", widget: "string"}
      - {label: "Foreground", name: "foreground", widget: "image"}
      - {label: "Background", name: "background", widget: "image"}
      - {label: "Content Module", name: "contentModule", widget: "list", fields: [{label: Date, name: date, widget: datetime, dateFormat: 'DD.MM.YYYY', timeFormat: 'HH:mm', pickerUtc: false }, {label: "Post Type", name: "posttype", widget: "select", options: ["web","jp","other"], default: ["web"]}, {label: "Publish Type", name: "publishtype", widget: "select", options: ["Draft","Publish"], default: ["Publish"]},{label: Heading, name: heading, widget: string}, {label: Content, name: content, widget: markdown}, {label: Image, name: image, widget: image, required: false}]}

  - name: singleposts
    label: Single Post
    folder: src/pages/posts
    create: true
    slug: "{{year}}-{{heading}}"
    fields:
      - {label: "Heading", name: "header", widget: "string"}
      - {label: "Content", name: "content", widget: "markdown"}