backend:
  name: git-gateway
  repo: ehylam/gatsby-blog

media_folder: static/assets
public_folder: /assets

collections:
  - name: content
    label: Content
    folder: src/pages/contents
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{heading}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-module"}
      - {label: "Heading", name: "heading", widget: "string"}
      - {label: "Content Module", name: "contentModule", widget: "list", fields: [{label: Heading, name: heading, widget: string}, {label: Content, name: content, widget: markdown}, {label: Image, name: image, widget: image, required: false}]}